# Generated by Django 4.2.30 on 2026-05-17 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('outcome', 'Outcome')], max_length=20)),
                ('category', models.CharField(choices=[('sponsorship', 'Sponsorship'), ('competition_prize', 'Competition Prize'), ('workshop_income', 'Workshop Income'), ('student_payment_summary', 'Student Payment Summary'), ('tools', 'Tools'), ('travel', 'Travel'), ('competition_fees', 'Competition Fees'), ('rent', 'Rent'), ('salary', 'Salary'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=50)),
                ('custom_category', models.CharField(blank=True, help_text='Use this only when category is Other', max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academy_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
