# Generated by Django 4.2.30 on 2026-05-17 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_academytransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeTransaction',
            fields=[
            ],
            options={
                'verbose_name': 'Income',
                'verbose_name_plural': 'Income',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('academy.academytransaction',),
        ),
        migrations.CreateModel(
            name='OutcomeTransaction',
            fields=[
            ],
            options={
                'verbose_name': 'Outcome',
                'verbose_name_plural': 'Outcome',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('academy.academytransaction',),
        ),
    ]
