# Generated by Django 4.2.30 on 2026-05-20 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_incometransaction_outcometransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='academytransaction',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academytransaction',
            name='event_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='academytransaction',
            name='event_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='academytransaction',
            name='related_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academy_transactions', to='academy.student'),
        ),
    ]
